### ISSUE TITLE
RuntimeError: pStyle: Title

### ISSUE THREAD

**Issue by junxu-ai** [dogatana/docx2md#1]
Hi,

When i use "!python -m docx2md /content/temp.docx /content/temp.md" to convert the docx into MD in colab, it gives the following error:

Traceback (most recent call last):
File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.10/dist-packages/docx2md/main.py", line 104, in
main()
File "/usr/local/lib/python3.10/dist-packages/docx2md/main.py", line 27, in main
md_text = convert(docx, target_dir, media, args.md_table)
File "/usr/local/lib/python3.10/dist-packages/docx2md/main.py", line 94, in convert
return converter.convert()
File "/usr/local/lib/python3.10/dist-packages/docx2md/converter.py", line 36, in convert
self.parse_node(of, body)
File "/usr/local/lib/python3.10/dist-packages/docx2md/converter.py", line 58, in parse_node
self.parse_p(of, child)
File "/usr/local/lib/python3.10/dist-packages/docx2md/converter.py", line 205, in parse_p
raise RuntimeError("pStyle: " + style)
RuntimeError: pStyle: Title

I also attached the docx file as a reference.

[temp.docx](https://github.com/dogatana/docx2md/files/12396244/temp.docx)

Thanks.

**Comment by dogatana** [comment]
Hi, @junxu-ai 

Thank you for your report.

I just fixed the issue, but I forgot how to upload to pypi 😅
So I apreciate if you could install new one as following.


``` 
pip install git+https://github.com/dogatana/docx2md.git
```

**Comment by ghost** [comment]
Ran into the same error and tried to install from GitHub as you mentioned. But that resulted in an installation error:

```bash
Collecting git+https://github.com/dogatana/docx2md.git
  Cloning https://github.com/dogatana/docx2md.git to /tmp/pip-req-build-fqxuy2jd
  Running command git clone --filter=blob:none --quiet https://github.com/dogatana/docx2md.git /tmp/pip-req-build-fqxuy2jd
  Resolved https://github.com/dogatana/docx2md.git to commit a1f828d8aa814323226c6f95e9f7b470b9f4bbef
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-fqxuy2jd/setup.py", line 13, in <module>
          README = open(readme).read()
                   ^^^^^^^^^^^^^^^^^^^
        File "<frozen codecs>", line 322, in decode
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 1716: invalid start byte
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by dogatana** [comment]
@sjstoelting 

I've updated PyPI. I hope you can install well.
