### ISSUE TITLE
RuntimeError: pStyle: NormalWeb

### ISSUE THREAD

**Issue by digi604** [dogatana/docx2md#2]
raise RuntimeError("pStyle: " + style)
RuntimeError: pStyle: NormalWeb

**Comment by digi604** [comment]
[Free_Test_Data_1MB_DOCX-1.docx](https://github.com/dogatana/docx2md/files/12528144/Free_Test_Data_1MB_DOCX-1.docx)

**Comment by dogatana** [comment]
HI, @digi604 

Thank you for your report.
I added some features to handle the issue.
I appreciate if you could try the new one that is on this repository.

```
pip install git+https://github.com/dogatana/docx2md.git
```

**Comment by DanCranford** [comment]
Hey there - 

I ran into a similar issue but with a `Runtime Error: pStyle: ListParagraph`.  I tried to install the repo you posted in this thread but got an error with that.

```
Collecting git+https://github.com/dogatana/docx2md.git
  Cloning https://github.com/dogatana/docx2md.git to /tmp/pip-req-build-v4w2zzze
  Running command git clone --filter=blob:none --quiet https://github.com/dogatana/docx2md.git /tmp/pip-req-build-v4w2zzze
  Resolved https://github.com/dogatana/docx2md.git to commit b6cfe1c57b1362e77dafbd7beae87b3d3fc834c5
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-v4w2zzze/setup.py", line 13, in <module>
          README = open(readme).read()
        File "/opt/conda/lib/python3.9/codecs.py", line 322, in decode
          (result, consumed) = self._buffer_decode(data, self.errors, final)
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 1716: invalid start byte
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Note: you may need to restart the kernel to use updated packages.
```

**Comment by dogatana** [comment]
@DanCranford 

Thank you for the report.
The above messages seemds to show that pip tried to process README-jp.md and could not handle it on your environment.
I rename README-jp.md to jp-README.md and apprecieate if you could try again.

**Comment by marceletchart** [comment]
@dogatana 
I got the same error following this thread. I pulled the repo and tried a change to `setup.py` and it worked.
I changed this line:
`readme = os.path.join(os.path.dirname(__file__), "README.rst")`
to 
`readme = os.path.join(os.path.dirname(__file__), "README.md")`

Not sure if that'll help everyone, but it resolved the utf-8 decode error above.

**Comment by he-tizotte** [comment]
Dear all,

I tested a hotfix at the line 198 of converter.py , by replacing 
style[0]=="a"
 by
 isinstance(style[0], str)
 and the md file is correctly generated.
 
Cheers,
[converter.py.patch](https://github.com/dogatana/docx2md/files/14944175/converter.py.patch)

**Comment by LancelotGD** [comment]
I noticed the fixes above haven't been published to PyPI yet. Would you consider releasing an update? 
This would benefit many users who rely on pip installations.

**Comment by dogatana** [comment]
Hi, all.

Thank you for your suggenstions.
I've changed the packaging system and update PyPI.

I hope it works well.
